version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: always
    volumes:
      - frontend-dist:/usr/share/nginx/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-frontend
    restart: always
    ports:
      - "4200:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-network

volumes:
  frontend-dist:

networks:
  app-network:
    driver: bridge
