apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: mikeangeloo/apollo-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "host.docker.internal:8080"
